-- Criação da tabela no Oracle
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SENSOR_DATA CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE SENSOR_DATA (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PHOSPHORUS NUMBER(1),
  POTASSIUM  NUMBER(1),
  PH         NUMBER(4,2),
  HUMIDITY   NUMBER(5,2),
  IRRIGATION_STATUS VARCHAR2(10),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Inserção dos dados de exemplo
INSERT INTO SENSOR_DATA (PHOSPHORUS, POTASSIUM, PH, HUMIDITY, IRRIGATION_STATUS)
VALUES (1, 0, 6.8, 35.5, 'Ligada');

INSERT INTO SENSOR_DATA (PHOSPHORUS, POTASSIUM, PH, HUMIDITY, IRRIGATION_STATUS)
VALUES (1, 1, 6.5, 60.0, 'Desligada');

INSERT INTO SENSOR_DATA (PHOSPHORUS, POTASSIUM, PH, HUMIDITY, IRRIGATION_STATUS)
VALUES (0, 1, 4.9, 45.0, 'Ligada');

COMMIT;